### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by jwg4**
Hi Moy, these are fixes to the two bugs mentioned in #3.

To work on these bugs, I added several test cases. However, as I also changed the way that the tests were being run - using munit for C and pytest for Python, I haven't put these changes in the PR. If you are interested in using those test frameworks - they are both good - I can create another PR with those changes. If you prefer not to change how the tests run, but you would like to add my test cases, we could adapt them together.

For now you can run @ArthurKantor's two test cases manually to see that this patch fixes them.

### CODE REVIEW

**Comment by moygit** [comment]
@jwg4 yes please feel free to include your munit and pytest changes. Thanks!

**Comment by jwg4** [comment]
Hi Moy, it would be really good to have the python 3 version with these fixes on PyPI.

**Comment by jwg4** [comment]
I would be very happy to take over maintenance on GitHub and/or pypi.

**Comment by moygit** [comment]
Thanks, Jack! I'll close these issues and add a note to the README pointing at your fork.

**Pull request closed without merging**
